# -*- coding: utf-8 -*-
"""divisió

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d80Z3X0D8JgdO4v6ntE2sx-VNUlkCXJ5
"""

x = int(input("Introdueix el dividend: "))
y = int(input("Introdueix el divisor: "))

quocient = x // y
residu = x % y

print(f"Divisió: {x}/{y}")
print(f"Quocient: {quocient}")
print(f"Residu: {residu}")